version: '3'

# networks:
#   kafka-net:
#     driver: bridge

services:
  mongo:
    container_name: mongo4
    image: mongo:4
    environment:
      - MONGO_INITDB_DATABASE=newswatcher
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root5566
    ports:
      - '27017:27017'
    command: mongod --auth
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./volumes/mongo4/db:/data/db

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    # networks:
    #   - kafka-net
    ports:
      - "2181:2181"

  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.12-2.4.0
    # networks:
    #   - kafka-net
    ports:
      - "9092:9092"
    environment:
      # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./volumes/kafka/docker.sock:/var/run/docker.sock


  # rabbitmq:
  #     container_name: rabbit
  #     image: "rabbitmq:3.8-management"
  #     hostname: "rabbit"
  #     environment:
  #       - RABBITMQ_DEFAULT_USER=root
  #       - RABBITMQ_DEFAULT_PASS=root5566
  #     ports:
  #       - "15672:15672"
  #       - "5672:5672"
  #     # volumes:
  #     #   - ./rabbitmq/rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config

# services:
#   splunkenterprise:
#     #build: .
#     hostname: splunk-0804
#     image: splunk/splunk:8.0.4
#     environment:
#       SPLUNK_START_ARGS: --accept-license
#       SPLUNK_ENABLE_LISTEN: 9997
#       #SPLUNK_HOME:
#       #SPLUNK_ADD: tcp 1514
#     # volumes:
#     #   - ./volumes/opt-splunk-etc:/opt/splunk/etc
#     #   - ./volumes/opt-splunk-var:/opt/splunk/var
#     ports:
#       - "8000:8000"
#       - "9997:9997"
#       - "8088:8088"
#       - "8089:8089"
      #- "1514:1514"


  # elasticsearch:
  #   container_name: elasticsearch-740
  #   image: elasticsearch:7.4.0
  #   environment:
  #     - node.name=es01
  #     - cluster.name=es-docker-cluster
  #     #- discovery.seed_hosts=es02,es03
  #     - cluster.initial_master_nodes=es01
  #     - bootstrap.memory_lock=true
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #     - "9200:9200"
  #     - "9300:9300"
  #   volumes:
  #     - ./volumes/elasticsearch-740:/usr/share/elasticsearch/data
  #   networks:
  #     - esnet

  # kibana:
  #   image: kibana:7.4.0
  #   ports:
  #     - "5601:5601"
  #   networks:
  #     - esnet
  #   depends_on:
  #     - elasticsearch

  # grafana:
  #   container_name: grafana-700
  #   image: grafana/grafana:7.0.0
  #   ports:
  #     - "3030:3000"
  #   volumes:
  #     - ./volumes/grafana-700/:/var/lib/grafana
  #   #networks:
  #   extra_hosts:
  #     - "dockerhost:127.0.0.1"
  #   #network_mode: host
      #- grafana_net
    #network_mode: bridge

# networks:
#   grafana_net:
#     external: true
# # networks:
#   esnet:
#     driver: bridge

